### ISSUE TITLE
Cookie Monster Down

### ISSUE THREAD

**Issue by mrphlaep** [Aktanusa/CookieMonster#111]
Hey,

I am afraid Cookie Monster is not working at both of my devices. I heard on wiki that others have got the same problem, so i guess it is not just a missing update at my end. I hope you it will work again soon. 

Thanks for the great add-on. I am really enjoying cookie monster and i guess i am not able to play without it anymore.

Greetings

Philipp

**Comment by Franciszka** [comment]
It doesn't work for me too. There were recently some freezes, but overall it was working.

It would be great to have it fixed!
Thank you for your work Aktanusa.

Greetings,
Franciszka

**Comment by Andreasvb** [comment]
Seems there are some problems with github.io, the raw link works.

**Comment by Aktanusa** [comment]
Well I fixed it again, which is probably temporary.  I need to contact github, but I'm thinking now that Cookie Monster got too popular and I need to find a new host...

**Comment by mrphlaep** [comment]
Hey again,

it is working again on my computer. 
I hope it'll be working for a while :) 

Thanks a lot for the quick response.
I greatly appreciate your service. 


Greetings

Philipp

**Comment by Otetz** [comment]
Still not working for me :(
404 for http://aktanusa.github.io/CookieMonster/queue/queue.js
```
CookieMonster.js:29 GET http://aktanusa.github.io/CookieMonster/queue/queue.js 
CM.Cache.AddQueue @ CookieMonster.js:29
CM.Init @ CookieMonster.js:2528
(anonymous function) @ CookieMonster.js:3104
```

**Comment by Aktanusa** [comment]
github responded and said they are working on it.  I think it is finally fixed.  Let me know if it still isn't working.

**Comment by Aktanusa** [comment]
I think this is fixed now =)
