### ISSUE TITLE
2.0109: Garden Info pop-up flickers on hover

### ISSUE THREAD

**Issue by danhd123** [Aktanusa/CookieMonster#209]
It flickers like it's trying to reposition itself and failing.

**Comment by Aktanusa** [comment]
What version of Cookie Monster are you using?  The reason why I ask is because the beta version of Cookie Monster is outdated and has that problem while the live version does not.

**Comment by danhd123** [comment]
Whatever version is hosted at http://aktanusa.github.io/CookieMonster/CookieMonster.js

**Comment by Aktanusa** [comment]
Weird, I didn't get a notification, but a new version is out around that time.  Try that out and let me know.  That does seem like the live version you used, in which the problem should have been fixed already.

**Comment by danhd123** [comment]
Still happening. Mac OS X 10.13.6, Safari 11.1.1 (13605.2.8)

**Comment by Aktanusa** [comment]
Dang, okay.  What's going to make it real hard is that I am on Windows and no way to test on Safari.  Hmm, would it be possible to make a desktop capture video of the problem?

**Comment by Aktanusa** [comment]
Did it work fine on the older version of CC?  This is not going to be easy ~_~

**Comment by danhd123** [comment]
You know what, never mind, this is broken in CC proper, not just Cookie Monster.

**Comment by Aktanusa** [comment]
Ah, well at least it's somewhat nice to know it's not CM, lol.
