### ISSUE TITLE
Golden Cookie alert breaks after first cookie

### ISSUE THREAD

**Issue by oplosthee** [Aktanusa/CookieMonster#405]
After today's update I have noticed that the golden cookie alert no longer works after the first cookie. The favicon stays gold after the first cookie has been clicked, and cookies after the first no longer play a sound after spawning. The "Next cookie" tracker still works fine.

I have tried the dev version as per the instructions in the readme, which does not appear to have this issue. However, it looks like the dev version still uses the old `CheckGoldenCookie` (if that's where the issue is).

**Comment by bitsandbytes1708** [comment]
It looks like the checkGoldenCookie functions are the same in both master and dev...can you elaborate?

**Comment by MMelnikoff** [comment]
I can confirm this is occurring to me too.  Golden Cookies are no longer producing a screen flash or sound effect despite the options being enabled in the options section.

**Comment by DanielNoord** [comment]
This should now be fixed upon reloading the mod.
Please let me know if anything else is broken!

**Comment by oplosthee** [comment]
I'm still experiencing the same issue running the script from https://aktanusa.github.io/CookieMonster/CookieMonster.js, which I believe includes the fixes from #409.

I have noticed that the timer on the golden cookies is not appearing either, but the timer in the `<title>` is updated accordingly. The favicon also changes into a golden cookie upon loading the script (and stays that way), but I'm not sure whether that's a bug.

**Comment by sewcioj** [comment]
> The favicon also changes into a golden cookie upon loading the script (and stays that way), but I'm not sure whether that's a bug.

I think it is - favicon is supposed to change accordingly when golden/wrath cookie appears, but ATM it doesn't.

**Comment by DanielNoord** [comment]
So sorry all, I have finally fixed it.
I have been working on a complete rewrite of that part of the code and messed up the structure of both versions in my head.

The fav-icon is still bugged out, but for now I think this is only a minor issue and it will be tackled with the rewrite.
Once again, so sorry for all inconvenience!

**Comment by oplosthee** [comment]
Seems to have been fixed now!

No worries, thanks a lot for your quick responses and hard work!
